### ISSUE TITLE
下ネタをブロックしよう！

### ISSUE THREAD

**Issue by kinoko2k** [seichi915Network/seichi915Chat#1]
下ネタ(うんこ・ちんことか)を`**`とかにして。見れないようにしてほしい

**Comment by stouma915** [comment]
完全に防ぐには下ネタガチ勢を呼ばないといけませんし、人によって〇〇は下ネタであるかどうかみたいなものは違う可能性があるので、自分でマスクする単語を追加できる禁止辞書なるものを実装予定です
