### ISSUE TITLE
&1とかで、文字に色を付けたりできるようにしてほしい

### ISSUE THREAD

**Issue by kinoko2k** [seichi915Network/seichi915Chat#6]
某Pluginで&1とかやったら、黒が出たりしてほしい

**Comment by stouma915** [comment]
実装済みです
![image](https://user-images.githubusercontent.com/62248740/111905398-c3ce5300-8a8e-11eb-824e-6ec3a3704569.png)

**Comment by kinoko2k** [comment]
naruhodp
